/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

//BELOW THIS IS VERY IMPORTANT MUST ADD THIS
//ALSO REMEMBER THIS IS LOCAL TO "PUBLIC" NOT RELATIVE!!!
export function Robot(props) {
  const { nodes, materials } = useGLTF(
    "./models/robot/phantoms-transformed.glb"
  );
  const robot = useRef();

  const scroll = useScroll();

  const tl = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());

    tl.current
      .to(robot.current.rotation, { y: -1 }, 2)
      .to(robot.current.position, { x: 1 }, 2)

      .to(robot.current.rotation, { y: 1 }, 10)
      .to(robot.current.position, { x: -1 }, 10)

      .to(robot.current.rotation, { y: 0 }, 20)
      .to(robot.current.rotation, { x: 1 }, 20)
      .to(robot.current.position, { x: 0 }, 20)

      .to(robot.current.rotation, { y: 0 }, 30)
      .to(robot.current.rotation, { x: -13 }, 30)
      .to(robot.current.position, { x: 0 }, 30)

      .to(robot.current.rotation, { y: 0 }, 50)
      .to(robot.current.rotation, { x: 0 }, 50)
      .to(robot.current.position, { x: 0 }, 50)

      .to(robot.current.rotation, { y: 0 }, 60)
      .to(robot.current.rotation, { x: 0 }, 60)
      .to(robot.current.position, { x: 0 }, 60);
  });

  useLayoutEffect(() => {
    //THIS IS THE GSAP GLUE CONNECTION!!!
    tl.current = gsap.timeline({
      defaults: { duration: 8, ease: "power1.inOut" },
    });
  }, []);

  return (
    //HERE YOU ARE LINKING THE ROBOT MODEL WITH "ref"
    //AND BELOW YOU ARE DESCRIBING THE MATERIALS AND FEEL OF ROBOT SURFACE LOOK
    <group {...props} dispose={null} ref={robot}>
      <group
        position={[-0.214, 0.163, 0.365]}
        rotation={[0, -0.152, 0]}
        scale={0.146}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Metal}
        >
          <meshPhysicalMaterial
            color="#aaa"
            roughness={0.2}
            metalness={1}
            reflectivity={0.5}
            iridescence={0.3}
            iridescenceIOR={1}
            iridescenceThicknessRange={[100, 1000]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.Material}
        >
          <meshPhysicalMaterial
            color="#000000"
            roughness={1}
            clearcoat={1}
            emissive={"#000"}
            metalness={0}
            reflectivity={0.2}
            iridescence={0.1}
            iridescenceIOR={1}
            iridescenceThicknessRange={[100, 1000]}
          />
        </mesh>
      </group>
    </group>
  );
}

//BELOW THIS IS VERY IMPORTANT MUST ADD THIS
useGLTF.preload("./models/robot/phantoms-transformed.glb");
